create table if not exists public.profiles (
  user_id uuid primary key references neon_auth."user"(id) on delete cascade,
  email text,
  stripe_customer_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  user_id uuid primary key references neon_auth."user"(id) on delete cascade,
  favorites text[] not null default '{}',
  last_room text not null default 'rooftop',
  last_track integer not null default 0 check (last_track between 0 and 2),
  volume integer not null default 72 check (volume between 0 and 100),
  muted boolean not null default false,
  timer_end timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  user_id uuid primary key references neon_auth."user"(id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text unique,
  plan text not null default 'unknown',
  status text not null default 'inactive',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references neon_auth."user"(id) on delete set null,
  session_id text,
  event_name text not null,
  room_slug text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_event_name_idx on public.analytics_events(event_name);
create index if not exists subscriptions_customer_idx on public.subscriptions(stripe_customer_id);
