create table if not exists public.broadcasts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  status text not null default 'draft' check (status in ('draft','ready','live','paused','ended')),
  brief text not null default '',
  active_persona_id uuid,
  planner_seed text not null default 'afterlight-broadcast-v1',
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ended_at is null or started_at is null or ended_at >= started_at)
);

create table if not exists public.broadcast_items (
  id uuid primary key default gen_random_uuid(),
  broadcast_id uuid not null references public.broadcasts(id) on delete cascade,
  ordinal integer not null check (ordinal >= 0),
  kind text not null check (kind in ('track','break','ident','segment')),
  source_id text,
  source_room text,
  title text,
  artist text,
  state text not null default 'planned' check (state in ('planned','ready','handed','airing','played','skipped','removed')),
  selection_reason jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz,
  started_at timestamptz,
  ended_at timestamptz,
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (broadcast_id, ordinal),
  check ((kind='track' and source_id is not null) or kind<>'track')
);

create table if not exists public.broadcast_events (
  id bigint generated by default as identity primary key,
  broadcast_id uuid not null references public.broadcasts(id) on delete cascade,
  broadcast_item_id uuid references public.broadcast_items(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  actor text not null default 'director',
  command_id text unique,
  created_at timestamptz not null default now()
);

create index if not exists broadcasts_status_created_idx on public.broadcasts(status,created_at desc);
create index if not exists broadcast_items_broadcast_ordinal_idx on public.broadcast_items(broadcast_id,ordinal);
create index if not exists broadcast_items_broadcast_state_idx on public.broadcast_items(broadcast_id,state,ordinal);
create index if not exists broadcast_events_broadcast_created_idx on public.broadcast_events(broadcast_id,created_at desc);

create unique index if not exists broadcasts_one_live_idx on public.broadcasts ((status)) where status='live';
